miscreg_map={'dbgdtrrxext': 'osdtrrx_el1', 'dbgdscrext': 'mdscr_el1', 'dbgdtrtxext': 'osdtrtx_el1', 'dbgoseccr': 'oseccr_el1', 'dbgbxvr0': 'dbgbvr0_el1', 'dbgbxvr1': 'dbgbvr1_el1', 'dbgbxvr2': 'dbgbvr2_el1', 'dbgbxvr3': 'dbgbvr3_el1', 'dbgbxvr4': 'dbgbvr4_el1', 'dbgbxvr5': 'dbgbvr5_el1', 'dbgbxvr6': 'dbgbvr6_el1', 'dbgbxvr7': 'dbgbvr7_el1', 'dbgbxvr8': 'dbgbvr8_el1', 'dbgbxvr9': 'dbgbvr9_el1', 'dbgbxvr10': 'dbgbvr10_el1', 'dbgbxvr11': 'dbgbvr11_el1', 'dbgbxvr12': 'dbgbvr12_el1', 'dbgbxvr13':
        'dbgbvr13_el1', 'dbgbxvr14': 'dbgbvr14_el1', 'dbgbxvr15': 'dbgbvr15_el1', 'dbgbcr0': 'dbgbcr0_el1', 'dbgbcr1': 'dbgbcr1_el1', 'dbgbcr2': 'dbgbcr2_el1', 'dbgbcr3': 'dbgbcr3_el1', 'dbgbcr4': 'dbgbcr4_el1', 'dbgbcr5': 'dbgbcr5_el1', 'dbgbcr6': 'dbgbcr6_el1', 'dbgbcr7': 'dbgbcr7_el1', 'dbgbcr8': 'dbgbcr8_el1', 'dbgbcr9': 'dbgbcr9_el1', 'dbgbcr10': 'dbgbcr10_el1', 'dbgbcr11': 'dbgbcr11_el1', 'dbgbcr12': 'dbgbcr12_el1', 'dbgbcr13': 'dbgbcr13_el1', 'dbgbcr14': 'dbgbcr14_el1', 'dbgbcr15':
        'dbgbcr15_el1', 'dbgwvr0': 'dbgwvr0_el1', 'dbgwvr1': 'dbgwvr1_el1', 'dbgwvr2': 'dbgwvr2_el1', 'dbgwvr3': 'dbgwvr3_el1', 'dbgwvr4': 'dbgwvr4_el1', 'dbgwvr5': 'dbgwvr5_el1', 'dbgwvr6': 'dbgwvr6_el1', 'dbgwvr7': 'dbgwvr7_el1', 'dbgwvr8': 'dbgwvr8_el1', 'dbgwvr9': 'dbgwvr9_el1', 'dbgwvr10': 'dbgwvr10_el1', 'dbgwvr11': 'dbgwvr11_el1', 'dbgwvr12': 'dbgwvr12_el1', 'dbgwvr13': 'dbgwvr13_el1', 'dbgwvr14': 'dbgwvr14_el1', 'dbgwvr15': 'dbgwvr15_el1', 'dbgwcr0': 'dbgwcr0_el1', 'dbgwcr1':
        'dbgwcr1_el1', 'dbgwcr2': 'dbgwcr2_el1', 'dbgwcr3': 'dbgwcr3_el1', 'dbgwcr4': 'dbgwcr4_el1', 'dbgwcr5': 'dbgwcr5_el1', 'dbgwcr6': 'dbgwcr6_el1', 'dbgwcr7': 'dbgwcr7_el1', 'dbgwcr8': 'dbgwcr8_el1', 'dbgwcr9': 'dbgwcr9_el1', 'dbgwcr10': 'dbgwcr10_el1', 'dbgwcr11': 'dbgwcr11_el1', 'dbgwcr12': 'dbgwcr12_el1', 'dbgwcr13': 'dbgwcr13_el1', 'dbgwcr14': 'dbgwcr14_el1', 'dbgwcr15': 'dbgwcr15_el1', 'dbgdscrint': 'mdccsr_el0', 'dbgvcr': 'dbgvcr32_el2', 'dbgdrar': 'mdrar_el1',
        'dbgoslar': 'oslar_el1', 'dbgoslsr': 'oslsr_el1', 'dbgosdlr': 'osdlr_el1', 'dbgprcr': 'dbgprcr_el1', 'dbgclaimset': 'dbgclaimset_el1', 'dbgclaimclr': 'dbgclaimclr_el1', 'dbgauthstatus': 'dbgauthstatus_el1', 'id_pfr0': 'id_pfr0_el1', 'id_pfr1': 'id_pfr1_el1', 'id_dfr0': 'id_dfr0_el1', 'id_afr0': 'id_afr0_el1', 'id_mmfr0': 'id_mmfr0_el1', 'id_mmfr1': 'id_mmfr1_el1', 'id_mmfr2': 'id_mmfr2_el1', 'id_mmfr3': 'id_mmfr3_el1', 'id_mmfr4': 'id_mmfr4_el1', 'id_isar0': 'id_isar0_el1',
        'id_isar1': 'id_isar1_el1', 'id_isar2': 'id_isar2_el1', 'id_isar3': 'id_isar3_el1', 'id_isar4': 'id_isar4_el1', 'id_isar5': 'id_isar5_el1', 'id_isar6': 'id_isar6_el1', 'csselr_ns': 'csselr_el1', 'vpidr': 'vpidr_el2', 'vmpidr': 'vmpidr_el2', 'sctlr_ns': 'sctlr_el1', 'actlr_ns': 'actlr_el1', 'cpacr': 'cpacr_el1', 'hsctlr': 'sctlr_el2', 'hactlr': 'actlr_el2', 'hcr2': 'hcr_el2', 'hdcr': 'mdcr_el2', 'hcptr': 'cptr_el2', 'hstr': 'hstr_el2', 'hacr': 'hacr_el2', 'scr': 'scr_el3',
        'sder': 'sder32_el3', 'sdcr': 'mdcr_el3', 'ttbr0_ns': 'ttbr0_el1', 'ttbr1_ns': 'ttbr1_el1', 'ttbcr_ns': 'tcr_el1', 'httbr': 'ttbr0_el2', 'htcr': 'tcr_el2', 'vttbr': 'vttbr_el2', 'vtcr': 'vtcr_el2', 'dacr_ns': 'dacr32_el2', 'spsr_svc': 'spsr_el1', 'spsr_hyp': 'spsr_el2', 'spsr_mon': 'spsr_el3', 'adfsr_ns': 'afsr0_el1', 'aifsr_ns': 'afsr1_el1', 'ifsr_ns': 'ifsr32_el2', 'hadfsr': 'afsr0_el2', 'haifsr': 'afsr1_el2', 'hsr': 'esr_el2', 'fpexc': 'fpexc32_el2', 'ifar_ns': 'far_el1', 'hifar':
        'far_el2', 'hpfar': 'hpfar_el2', 'par_ns': 'par_el1', 'pmintenset': 'pmintenset_el1', 'pmintenclr': 'pmintenclr_el1', 'pmcr': 'pmcr_el0', 'pmcntenset': 'pmcntenset_el0', 'pmcntenclr': 'pmcntenclr_el0', 'pmovsclr': 'pmovsclr_el0', 'pmswinc': 'pmswinc_el0', 'pmselr': 'pmselr_el0', 'pmceid0': 'pmceid0_el0', 'pmceid1': 'pmceid1_el0', 'pmccntr': 'pmccntr_el0', 'pmxevtyper': 'pmxevtyper_el0', 'pmxevcntr': 'pmxevcntr_el0', 'pmuserenr': 'pmuserenr_el0', 'pmovsset': 'pmovsset_el0',
        'nmrr_ns': 'mair_el1', 'amair1_ns': 'amair_el1', 'hmair1': 'mair_el2', 'hamair1': 'amair_el2', 'vbar_ns': 'vbar', 'hvbar': 'vbar_el2', 'contextidr_ns': 'contextidr_el1', 'tpidrprw_ns': 'tpidr_el1', 'tpidrurw_ns': 'tpidr_el0', 'tpidruro_ns': 'tpidrro_el0', 'htpidr': 'tpidr_el2', 'cntfrq': 'cntfrq_el0', 'cntpct': 'cntpct_el0', 'cntvct': 'cntvct_el0', 'cntp_ctl_ns': 'cntp_ctl_el02', 'cntp_cval_ns': 'cntp_cval_el02', 'cntp_tval_ns': 'cntp_tval_el02', 'cntv_ctl':
        'cntv_ctl_el02', 'cntv_cval': 'cntv_cval_el02', 'cntv_tval': 'cntv_tval_el02', 'cntkctl': 'cntkctl_el1', 'cnthctl': 'cnthctl_el2', 'cnthp_ctl': 'cnthp_ctl_el2', 'cnthp_cval': 'cnthp_cval_el2', 'cnthp_tval': 'cnthp_tval_el2', 'cntvoff': 'cntvoff_el2', 'pmevcntr0': 'pmevcntr0_el0', 'pmevcntr1': 'pmevcntr1_el0', 'pmevcntr2': 'pmevcntr2_el0', 'pmevcntr3': 'pmevcntr3_el0', 'pmevcntr4': 'pmevcntr4_el0', 'pmevcntr5': 'pmevcntr5_el0', 'pmevtyper0': 'pmevtyper0_el0', 'pmevtyper1':
        'pmevtyper1_el0', 'pmevtyper2': 'pmevtyper2_el0', 'pmevtyper3': 'pmevtyper3_el0', 'pmevtyper4': 'pmevtyper4_el0', 'pmevtyper5': 'pmevtyper5_el0', 'icc_pmr': 'icc_pmr_el1', 'icc_iar0': 'icc_iar0_el1', 'icc_eoir0': 'icc_eoir0_el1', 'icc_hppir0': 'icc_hppir0_el1', 'icc_bpr0': 'icc_bpr0_el1', 'icc_ap0r0': 'icc_ap0r0_el1', 'icc_ap0r1': 'icc_ap0r1_el1', 'icc_ap0r2': 'icc_ap0r2_el1', 'icc_ap0r3': 'icc_ap0r3_el1', 'icc_ap1r0': 'icc_ap1r0_el1', 'icc_ap1r0_ns': 'icc_ap1r0_el1_ns',
        'icc_ap1r0_s': 'icc_ap1r0_el1_s', 'icc_ap1r1': 'icc_ap1r1_el1', 'icc_ap1r1_ns': 'icc_ap1r1_el1_ns', 'icc_ap1r1_s': 'icc_ap1r1_el1_s', 'icc_ap1r2': 'icc_ap1r2_el1', 'icc_ap1r2_ns': 'icc_ap1r2_el1_ns', 'icc_ap1r2_s': 'icc_ap1r2_el1_s', 'icc_ap1r3': 'icc_ap1r3_el1', 'icc_ap1r3_ns': 'icc_ap1r3_el1_ns', 'icc_ap1r3_s': 'icc_ap1r3_el1_s', 'icc_dir': 'icc_dir_el1', 'icc_rpr': 'icc_rpr_el1', 'icc_sgi1r': 'icc_sgi1r_el1', 'icc_asgi1r': 'icc_asgi1r_el1', 'icc_sgi0r': 'icc_sgi0r_el1', 'icc_iar1':
        'icc_iar1_el1', 'icc_eoir1': 'icc_eoir1_el1', 'icc_hppir1': 'icc_hppir1_el1', 'icc_bpr1': 'icc_bpr1_el1', 'icc_bpr1_ns': 'icc_bpr1_el1_ns', 'icc_bpr1_s': 'icc_bpr1_el1_s', 'icc_ctlr': 'icc_ctlr_el1', 'icc_ctlr_ns': 'icc_ctlr_el1_ns', 'icc_ctlr_s': 'icc_ctlr_el1_s', 'icc_sre': 'icc_sre_el1', 'icc_sre_ns': 'icc_sre_el1_ns', 'icc_sre_s': 'icc_sre_el1_s', 'icc_igrpen0': 'icc_igrpen0_el1', 'icc_igrpen1': 'icc_igrpen1_el1', 'icc_igrpen1_ns': 'icc_igrpen1_el1_ns',
        'icc_igrpen1_s': 'icc_igrpen1_el1_s', 'icc_hsre': 'icc_sre_el2', 'icc_mctlr': 'icc_ctlr_el3', 'icc_msre': 'icc_sre_el3', 'icc_mgrpen1': 'icc_igrpen1_el3', 'ich_ap0r0': 'ich_ap0r0_el2', 'ich_ap0r1': 'ich_ap0r1_el2', 'ich_ap0r2': 'ich_ap0r2_el2', 'ich_ap0r3': 'ich_ap0r3_el2', 'ich_ap1r0': 'ich_ap1r0_el2', 'ich_ap1r1': 'ich_ap1r1_el2', 'ich_ap1r2': 'ich_ap1r2_el2', 'ich_ap1r3': 'ich_ap1r3_el2', 'ich_hcr': 'ich_hcr_el2', 'ich_vtr': 'ich_vtr_el2', 'ich_misr': 'ich_misr_el2',
        'ich_eisr': 'ich_eisr_el2', 'ich_elrsr': 'ich_elrsr_el2', 'ich_vmcr': 'ich_vmcr_el2', 'ich_lr0': 'ich_lrc0', 'ich_lr1': 'ich_lrc1', 'ich_lr2': 'ich_lrc2', 'ich_lr3': 'ich_lrc3', 'ich_lr4': 'ich_lrc4', 'ich_lr5': 'ich_lrc5', 'ich_lr6': 'ich_lrc6', 'ich_lr7': 'ich_lrc7', 'ich_lr8': 'ich_lrc8', 'ich_lr9': 'ich_lrc9', 'ich_lr10': 'ich_lrc10', 'ich_lr11': 'ich_lrc11', 'ich_lr13': 'ich_lrc13', 'ich_lr14': 'ich_lrc14', 'ich_lr15': 'ich_lrc15'}

intreg_list=[
    "x0", "x1", "x2", "x3", "x4", "x5", "x6", "x7",
    "x8", "x9", "x10", "x11", "x12", "x13", "x14", "0",
    "x19", "x18", "0", "0", "x15", "x21", "x20", "x23",
    "x22", "x17", "x16", "x24", "x25", "x26", "x27", "x28",
    "x29", "x30"
]
